### ISSUE TITLE
建库脚本

### ISSUE THREAD

**Issue by ambluse** [yonyou-auto-dev/microservice-mom#18]
整好脚本提供给客户端建消息表的脚本，包含不限于生产者的表和消费者的表 # @daniellhu

**Comment by daniellhu** [comment]
SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for consumer_msg
-- ----------------------------
DROP TABLE IF EXISTS `consumer_msg`;
CREATE TABLE `consumer_msg` (
  `msg_key` varchar(255) NOT NULL,
  `create_time` bigint(20) DEFAULT NULL,
  `exchange` varchar(255) DEFAULT NULL,
  `info_msg` varchar(255) DEFAULT NULL,
  `msg_content` varchar(255) DEFAULT NULL,
  `retry_count` int(11) DEFAULT NULL,
  `router_key` varchar(255) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `update_time` bigint(20) DEFAULT NULL,
  `biz_class_name` varchar(255) DEFAULT NULL,
  `consumer_class_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`msg_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for producer_msg
-- ----------------------------
DROP TABLE IF EXISTS `producer_msg`;
CREATE TABLE `producer_msg` (
  `msg_key` varchar(255) NOT NULL,
  `create_time` bigint(20) DEFAULT NULL,
  `exchange` varchar(255) DEFAULT NULL,
  `info_msg` varchar(255) DEFAULT NULL,
  `msg_content` varchar(255) DEFAULT NULL,
  `retry_count` int(11) DEFAULT NULL,
  `router_key` varchar(255) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `update_time` bigint(20) DEFAULT NULL,
  `biz_class_name` varchar(255) DEFAULT NULL,
  `version` int(11) NOT NULL,
  PRIMARY KEY (`msg_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
SET FOREIGN_KEY_CHECKS=1;

**Comment by ambluse** [comment]
这个脚本不行 请提供类似 这样的脚本
CREATE TABLE `mom_data` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`create_time` VARCHAR(14) NOT NULL,
	`update_time` VARCHAR(14) NOT NULL,
	`msg_key` CHAR(36) NOT NULL COMMENT '唯一标识',
	`data` MEDIUMTEXT NOT NULL COMMENT '最大16MB，UTF-8',
	`status` TINYINT(4) NOT NULL DEFAULT '0',
	`info_msg` VARCHAR(256) NOT NULL DEFAULT '',
	`consume_time` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '上次消耗时间，精确到毫妙',
	`retryCount` INT(11) NOT NULL DEFAULT '0' COMMENT '重试次数',
	`exchange` VARCHAR(50) NOT NULL DEFAULT '',
	`routerKey` VARCHAR(50) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`),
	INDEX `correlation_id` (`correlation`),
	INDEX `status` (`status`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

写清楚备注，定义清楚长度，定义清楚字段的默认值

**Comment by ambluse** [comment]
[https://github.com/yonyou-auto-dev/microservice-mom/tree/master/mom-client/mom-client/sql](url)
